[env:d1_mini_esp32]
platform = espressif32
board = wemos_d1_mini32     
framework = espidf

; Serial Monitor
monitor_speed = 115200

build_flags =
    -I include
    -D DEBUG=1
    -D BAUD_RATE=115200

; OTA Upload
; upload_protocol = espota
; upload_port = <fill later>